apiVersion: v1
kind: Secret
metadata:
  name: burgeriam-secrets
  namespace: burgeriam
type: Opaque
stringData:
  jwt-key: "BurgerIAM-SuperSecret-Key-Min32Chars!"
  rabbitmq-username: "guest"
  rabbitmq-password: "guest"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: burgeriam
type: Opaque
stringData:
  rabbitmq-password: "guest"
